spring:
  application:
    name: kafkaTopicListener

server:
  port: 8080

kafka:
  bootstrap-servers: localhost:9092
  properties:
#    max.poll.records: 100
#    max.poll.interval.ms: 300000

kafkaTopicName: my-topic
kafkaGroupId: my-group

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
